name = "siyuan-tasknote-payment"
main = "src/index.js"
compatibility_date = "2024-01-01"
routes = [
  { zone_name = "achuan-2.top", pattern = "siyuan-tasknote.achuan-2.top", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_id = "a599b253-8bcc-4fd7-be5d-d9cc3cbcc112"  # 替换为第四步得到的 database_id

[vars]
PID = "2026020416153010"  # 你的zpay商户ID
ZPAY_API_BASE = "https://zpayz.cn"

